// <auto-generated />
using System;
using System.Collections.Generic;
using System.Net;
using JSEA_Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JSEA_Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260210133611_InitFullDatabase")]
    partial class InitFullDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "action_type", "action_type", new[] { "create", "update", "delete", "verify", "feature", "reject", "login", "logout" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "experience_status", "experience_status", new[] { "active_unverified", "verified", "featured", "needs_update", "inactive", "rejected" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "interaction_type", "interaction_type", new[] { "accepted", "skipped", "saved", "viewed_details" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "journey_status", "journey_status", new[] { "planning", "in_progress", "completed", "cancelled" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "mood_type", "mood_type", new[] { "relax", "photography", "foodie", "adventure", "culture" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "notification_type", "notification_type", new[] { "experience_verified", "featured", "rejected", "time_budget_warning" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "package_type", "package_type", new[] { "basic", "pro" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "recurrence_pattern", "recurrence_pattern", new[] { "once", "daily", "weekly", "monthly", "yearly", "custom" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "season_type", "season_type", new[] { "year_round", "summer", "autumn", "winter", "spring" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "time_of_day", "time_of_day", new[] { "morning", "afternoon", "evening", "night" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "transaction_status", "transaction_status", new[] { "pending", "completed", "failed", "refunded" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "transaction_type", "transaction_type", new[] { "purchase", "renewal", "upgrade" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_role", "user_role", new[] { "traveler", "staff", "admin" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_status", "user_status", new[] { "pending_verification", "active", "suspended", "deleted" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "vehicle_type", "vehicle_type", new[] { "walking", "bicycle", "motorbike", "car" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "weather_type", "weather_type", new[] { "sunny", "cloudy", "rainy" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "fuzzystrmatch");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JSEA_Application.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("ActionType")
                        .HasColumnType("integer")
                        .HasColumnName("action_type");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<IPAddress>("IpAddress")
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<string>("NewValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_values");

                    b.Property<string>("OldValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_values");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("audit_logs_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("audit_logs");
                });

            modelBuilder.Entity("JSEA_Application.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("icon_url");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("categories_pkey");

                    b.HasIndex(new[] { "Name" }, "categories_name_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Slug" }, "categories_slug_key")
                        .IsUnique();

                    b.ToTable("categories");
                });

            modelBuilder.Entity("JSEA_Application.Models.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndDatetime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_datetime");

                    b.Property<string>("EventType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<Guid?>("ExperienceId")
                        .HasColumnType("uuid")
                        .HasColumnName("experience_id");

                    b.Property<int?>("RecurrencePattern")
                        .HasColumnType("integer")
                        .HasColumnName("recurrence_pattern");

                    b.Property<string>("RecurrenceRule")
                        .HasColumnType("text")
                        .HasColumnName("recurrence_rule");

                    b.Property<decimal?>("ScoreBoostFactor")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("score_boost_factor");

                    b.Property<DateTime?>("StartDatetime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_datetime");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<Guid?>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id")
                        .HasName("events_pkey");

                    b.HasIndex("ExperienceId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("events");
                });

            modelBuilder.Entity("JSEA_Application.Models.EventOccurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTime?>("OccurrenceEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurrence_end");

                    b.Property<DateTime?>("OccurrenceStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurrence_start");

                    b.HasKey("Id")
                        .HasName("event_occurrences_pkey");

                    b.HasIndex("EventId");

                    b.ToTable("event_occurrences");
                });

            modelBuilder.Entity("JSEA_Application.Models.ExperienceDetail", b =>
                {
                    b.Property<Guid>("ExperienceId")
                        .HasColumnType("uuid")
                        .HasColumnName("experience_id");

                    b.Property<string>("AccessibilityInfo")
                        .HasColumnType("text")
                        .HasColumnName("accessibility_info");

                    b.Property<string>("CrowdLevel")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("crowd_level");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("FeaturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("featured_at");

                    b.Property<Guid?>("FeaturedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("featured_by_user_id");

                    b.Property<string>("ModerationNotes")
                        .HasColumnType("text")
                        .HasColumnName("moderation_notes");

                    b.Property<string>("OpeningHours")
                        .HasColumnType("jsonb")
                        .HasColumnName("opening_hours");

                    b.Property<string>("PriceRange")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("price_range");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("SafetyNotes")
                        .HasColumnType("text")
                        .HasColumnName("safety_notes");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.Property<Guid?>("VerifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("verified_by_user_id");

                    b.HasKey("ExperienceId")
                        .HasName("experience_details_pkey");

                    b.HasIndex("FeaturedByUserId");

                    b.HasIndex("VerifiedByUserId");

                    b.ToTable("experience_details");
                });

            modelBuilder.Entity("JSEA_Application.Models.ExperienceMetric", b =>
                {
                    b.Property<Guid>("ExperienceId")
                        .HasColumnType("uuid")
                        .HasColumnName("experience_id");

                    b.Property<decimal?>("AcceptanceRate")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("acceptance_rate");

                    b.Property<decimal?>("AvgRating")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(2, 1)
                        .HasColumnType("numeric(2,1)")
                        .HasColumnName("avg_rating")
                        .HasDefaultValueSql("0");

                    b.Property<decimal?>("FeaturedScore")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("featured_score");

                    b.Property<DateTime?>("LastVisitDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_visit_date");

                    b.Property<int?>("TotalRatings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_ratings");

                    b.Property<int?>("TotalVisits")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_visits");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ExperienceId")
                        .HasName("experience_metrics_pkey");

                    b.ToTable("experience_metrics");
                });

            modelBuilder.Entity("JSEA_Application.Models.ExperiencePhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Caption")
                        .HasColumnType("text")
                        .HasColumnName("caption");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<Guid?>("ExperienceId")
                        .HasColumnType("uuid")
                        .HasColumnName("experience_id");

                    b.Property<bool?>("IsCover")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_cover");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("photo_url");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("thumbnail_url");

                    b.Property<Guid?>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id")
                        .HasName("experience_photos_pkey");

                    b.HasIndex("ExperienceId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("experience_photos");
                });

            modelBuilder.Entity("JSEA_Application.Models.Feedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("ExperienceId")
                        .HasColumnType("uuid")
                        .HasColumnName("experience_id");

                    b.Property<string>("FeedbackText")
                        .HasColumnType("text")
                        .HasColumnName("feedback_text");

                    b.Property<string>("FlaggedReason")
                        .HasColumnType("text")
                        .HasColumnName("flagged_reason");

                    b.Property<bool?>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_approved");

                    b.Property<bool?>("IsFlagged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_flagged");

                    b.Property<Guid?>("TravelerId")
                        .HasColumnType("uuid")
                        .HasColumnName("traveler_id");

                    b.Property<Guid?>("VisitId")
                        .IsRequired()
                        .HasColumnType("uuid")
                        .HasColumnName("visit_id");

                    b.HasKey("Id")
                        .HasName("feedbacks_pkey");

                    b.HasIndex("ExperienceId");

                    b.HasIndex("TravelerId");

                    b.HasIndex(new[] { "VisitId" }, "feedbacks_visit_id_key")
                        .IsUnique();

                    b.ToTable("feedbacks");
                });

            modelBuilder.Entity("JSEA_Application.Models.Journey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int?>("ActualDistanceMeters")
                        .HasColumnType("integer")
                        .HasColumnName("actual_distance_meters");

                    b.Property<LineString>("ActualRoutePath")
                        .HasColumnType("geography(LineString,4326)")
                        .HasColumnName("actual_route_path");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("CurrentMood")
                        .HasColumnType("integer")
                        .HasColumnName("current_mood");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("destination_address");

                    b.Property<Point>("DestinationLocation")
                        .HasColumnType("geography(Point,4326)")
                        .HasColumnName("destination_location");

                    b.Property<int?>("EstimatedDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_duration_minutes");

                    b.Property<int?>("MaxDetourDistanceMeters")
                        .HasColumnType("integer")
                        .HasColumnName("max_detour_distance_meters");

                    b.Property<string>("OriginAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("origin_address");

                    b.Property<Point>("OriginLocation")
                        .HasColumnType("geography(Point,4326)")
                        .HasColumnName("origin_location");

                    b.Property<int?>("PreferredStopDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("preferred_stop_duration_minutes");

                    b.Property<LineString>("RoutePath")
                        .HasColumnType("geography(LineString,4326)")
                        .HasColumnName("route_path");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int?>("TimeBudgetMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("time_budget_minutes");

                    b.Property<int?>("TotalDistanceMeters")
                        .HasColumnType("integer")
                        .HasColumnName("total_distance_meters");

                    b.Property<Guid?>("TravelerId")
                        .HasColumnType("uuid")
                        .HasColumnName("traveler_id");

                    b.Property<int>("VehicleType")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_type");

                    b.HasKey("Id")
                        .HasName("journeys_pkey");

                    b.HasIndex("TravelerId");

                    b.ToTable("journeys");
                });

            modelBuilder.Entity("JSEA_Application.Models.JourneySuggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int?>("DetourDistanceMeters")
                        .HasColumnType("integer")
                        .HasColumnName("detour_distance_meters");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<int?>("EstimatedStopMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_stop_minutes");

                    b.Property<Guid?>("ExperienceId")
                        .HasColumnType("uuid")
                        .HasColumnName("experience_id");

                    b.Property<Guid?>("JourneyId")
                        .HasColumnType("uuid")
                        .HasColumnName("journey_id");

                    b.Property<decimal?>("RelevanceScore")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("relevance_score");

                    b.Property<Guid?>("SegmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("segment_id");

                    b.Property<DateTime?>("SuggestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("suggested_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("journey_suggestions_pkey");

                    b.HasIndex("ExperienceId");

                    b.HasIndex("JourneyId");

                    b.HasIndex("SegmentId");

                    b.ToTable("journey_suggestions");
                });

            modelBuilder.Entity("JSEA_Application.Models.JourneyWaypoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("ActualArrivalAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actual_arrival_at");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<DateTime?>("EstimatedArrivalAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("estimated_arrival_at");

                    b.Property<Guid?>("ExperienceId")
                        .HasColumnType("uuid")
                        .HasColumnName("experience_id")
                        .HasComment("Có thể là 1 micro-experience hoặc điểm tùy chỉnh");

                    b.Property<Guid?>("JourneyId")
                        .HasColumnType("uuid")
                        .HasColumnName("journey_id");

                    b.Property<Point>("Location")
                        .HasColumnType("geography(Point,4326)")
                        .HasColumnName("location");

                    b.Property<int?>("StopOrder")
                        .HasColumnType("integer")
                        .HasColumnName("stop_order")
                        .HasComment("Thứ tự điểm dừng 1, 2, 3...");

                    b.HasKey("Id")
                        .HasName("journey_waypoints_pkey");

                    b.HasIndex("ExperienceId");

                    b.HasIndex("JourneyId");

                    b.ToTable("journey_waypoints");
                });

            modelBuilder.Entity("JSEA_Application.Models.MicroExperience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country")
                        .HasDefaultValueSql("'Vietnam'::character varying");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Point>("Location")
                        .HasColumnType("geography(Point,4326)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int[]>("PreferredTimes")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("preferred_times");

                    b.Property<int[]>("Seasonality")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("seasonality");

                    b.Property<string>("Slug")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("slug");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int[]>("SuitableMoods")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("suitable_moods");

                    b.Property<List<string>>("Tags")
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_user_id");

                    b.Property<int[]>("WeatherSuitability")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("weather_suitability");

                    b.HasKey("Id")
                        .HasName("micro_experiences_pkey");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UploadedByUserId");

                    b.HasIndex(new[] { "Slug" }, "micro_experiences_slug_key")
                        .IsUnique();

                    b.ToTable("micro_experiences");
                });

            modelBuilder.Entity("JSEA_Application.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<int>("NotificationType")
                        .HasColumnType("integer")
                        .HasColumnName("notification_type");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<Guid?>("RelatedExperienceId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_experience_id");

                    b.Property<Guid?>("RelatedJourneyId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_journey_id");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("notifications_pkey");

                    b.HasIndex("RelatedExperienceId");

                    b.HasIndex("RelatedJourneyId");

                    b.HasIndex("UserId");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("JSEA_Application.Models.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Benefit")
                        .HasColumnType("jsonb")
                        .HasColumnName("benefit")
                        .HasComment("Lưu các quyền lợi của gói");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool?>("IsPopular")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_popular");

                    b.Property<int?>("Km")
                        .HasColumnType("integer")
                        .HasColumnName("km")
                        .HasComment("Giới hạn km hoặc thuộc tính liên quan");

                    b.Property<decimal?>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price");

                    b.Property<decimal?>("SalePrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("sale_price");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("packages_pkey");

                    b.ToTable("packages");
                });

            modelBuilder.Entity("JSEA_Application.Models.Rating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("ExperienceId")
                        .HasColumnType("uuid")
                        .HasColumnName("experience_id");

                    b.Property<int?>("Rating1")
                        .HasColumnType("integer")
                        .HasColumnName("rating")
                        .HasComment("1-5 stars");

                    b.Property<Guid?>("TravelerId")
                        .HasColumnType("uuid")
                        .HasColumnName("traveler_id");

                    b.Property<Guid?>("VisitId")
                        .IsRequired()
                        .HasColumnType("uuid")
                        .HasColumnName("visit_id");

                    b.HasKey("Id")
                        .HasName("ratings_pkey");

                    b.HasIndex("ExperienceId");

                    b.HasIndex("TravelerId");

                    b.HasIndex(new[] { "VisitId" }, "ratings_visit_id_key")
                        .IsUnique();

                    b.ToTable("ratings");
                });

            modelBuilder.Entity("JSEA_Application.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("refresh_tokens_pkey");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "TokenHash" }, "refresh_tokens_token_hash_key")
                        .IsUnique();

                    b.ToTable("refresh_tokens");
                });

            modelBuilder.Entity("JSEA_Application.Models.RouteSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int?>("DistanceMeters")
                        .HasColumnType("integer")
                        .HasColumnName("distance_meters");

                    b.Property<int?>("EstimatedDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_duration_minutes");

                    b.Property<bool?>("IsBusy")
                        .HasColumnType("boolean")
                        .HasColumnName("is_busy");

                    b.Property<bool?>("IsCulturalArea")
                        .HasColumnType("boolean")
                        .HasColumnName("is_cultural_area");

                    b.Property<bool?>("IsScenic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_scenic");

                    b.Property<Guid?>("JourneyId")
                        .HasColumnType("uuid")
                        .HasColumnName("journey_id");

                    b.Property<int?>("SegmentOrder")
                        .HasColumnType("integer")
                        .HasColumnName("segment_order");

                    b.Property<LineString>("SegmentPath")
                        .HasColumnType("geography(LineString,4326)")
                        .HasColumnName("segment_path");

                    b.HasKey("Id")
                        .HasName("route_segments_pkey");

                    b.HasIndex("JourneyId");

                    b.ToTable("route_segments");
                });

            modelBuilder.Entity("JSEA_Application.Models.SuggestionInteraction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("InteractedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("interacted_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("InteractionType")
                        .HasColumnType("integer")
                        .HasColumnName("interaction_type");

                    b.Property<Guid?>("SuggestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("suggestion_id");

                    b.HasKey("Id")
                        .HasName("suggestion_interactions_pkey");

                    b.HasIndex("SuggestionId");

                    b.ToTable("suggestion_interactions");
                });

            modelBuilder.Entity("JSEA_Application.Models.SystemConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ConfigKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("config_key");

                    b.Property<string>("ConfigValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("config_value");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("system_configs_pkey");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex(new[] { "ConfigKey" }, "system_configs_config_key_key")
                        .IsUnique();

                    b.ToTable("system_configs");
                });

            modelBuilder.Entity("JSEA_Application.Models.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long?>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<string>("CheckoutUrl")
                        .HasColumnType("text")
                        .HasColumnName("checkout_url");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ItemSnapshot")
                        .HasColumnType("jsonb")
                        .HasColumnName("item_snapshot")
                        .HasComment("Lưu thông tin gói tại thời điểm mua");

                    b.Property<long?>("OrderCode")
                        .HasColumnType("bigint")
                        .HasColumnName("order_code");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<string>("PaymentLinkId")
                        .HasColumnType("text")
                        .HasColumnName("payment_link_id");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_method");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("WebhookData")
                        .HasColumnType("jsonb")
                        .HasColumnName("webhook_data");

                    b.HasKey("Id")
                        .HasName("transactions_pkey");

                    b.HasIndex("OrderCode")
                        .IsUnique()
                        .HasDatabaseName("transactions_order_code_key");

                    b.HasIndex("UserId");

                    b.ToTable("transactions");
                });

            modelBuilder.Entity("JSEA_Application.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("AuthProvider")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("auth_provider");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool?>("EmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("email_verified");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<bool?>("PhoneVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("phone_verified");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("provider_key");

                    b.Property<DateTime?>("ResetPasswordExpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reset_password_expiry");

                    b.Property<string>("ResetPasswordToken")
                        .HasColumnType("text")
                        .HasColumnName("reset_password_token");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex(new[] { "Email" }, "users_email_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Phone" }, "users_phone_key")
                        .IsUnique();

                    b.ToTable("users", null, t =>
                        {
                            t.HasComment("Quản lý authentication và phân quyền");
                        });
                });

            modelBuilder.Entity("JSEA_Application.Models.UserFavorite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ExperienceId")
                        .HasColumnType("uuid")
                        .HasColumnName("experience_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("user_favorites_pkey");

                    b.HasIndex("ExperienceId");

                    b.HasIndex("UserId");

                    b.ToTable("user_favorites");
                });

            modelBuilder.Entity("JSEA_Application.Models.UserPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("ActivatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<Guid?>("PackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("user_packages_pkey");

                    b.HasIndex("PackageId");

                    b.HasIndex("UserId");

                    b.ToTable("user_packages");
                });

            modelBuilder.Entity("JSEA_Application.Models.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AccessibilityNeeds")
                        .HasColumnType("text")
                        .HasColumnName("accessibility_needs");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("department");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<List<string>>("Interests")
                        .HasColumnType("text[]")
                        .HasColumnName("interests");

                    b.Property<string>("Permissions")
                        .HasColumnType("jsonb")
                        .HasColumnName("permissions");

                    b.Property<List<string>>("PreferredTravelStyles")
                        .HasColumnType("text[]")
                        .HasColumnName("preferred_travel_styles");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("user_profiles_pkey");

                    b.HasIndex(new[] { "UserId" }, "user_profiles_user_id_key")
                        .IsUnique();

                    b.ToTable("user_profiles", null, t =>
                        {
                            t.HasComment("Metadata chi tiết cho từng loại user");
                        });
                });

            modelBuilder.Entity("JSEA_Application.Models.Visit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int?>("ActualDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("actual_duration_minutes");

                    b.Property<Guid?>("ExperienceId")
                        .HasColumnType("uuid")
                        .HasColumnName("experience_id");

                    b.Property<Guid?>("JourneyId")
                        .HasColumnType("uuid")
                        .HasColumnName("journey_id");

                    b.Property<List<string>>("PhotoUrls")
                        .HasColumnType("text[]")
                        .HasColumnName("photo_urls");

                    b.Property<Guid?>("TravelerId")
                        .HasColumnType("uuid")
                        .HasColumnName("traveler_id");

                    b.Property<DateTime?>("VisitedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("visited_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("visits_pkey");

                    b.HasIndex("ExperienceId");

                    b.HasIndex("JourneyId");

                    b.HasIndex("TravelerId");

                    b.ToTable("visits");
                });

            modelBuilder.Entity("JSEA_Application.Models.AuditLog", b =>
                {
                    b.HasOne("JSEA_Application.Models.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("audit_logs_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JSEA_Application.Models.Event", b =>
                {
                    b.HasOne("JSEA_Application.Models.MicroExperience", "Experience")
                        .WithMany("Events")
                        .HasForeignKey("ExperienceId")
                        .HasConstraintName("events_experience_id_fkey");

                    b.HasOne("JSEA_Application.Models.User", "UploadedByUser")
                        .WithMany("Events")
                        .HasForeignKey("UploadedByUserId")
                        .HasConstraintName("events_uploaded_by_user_id_fkey");

                    b.Navigation("Experience");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("JSEA_Application.Models.EventOccurrence", b =>
                {
                    b.HasOne("JSEA_Application.Models.Event", "Event")
                        .WithMany("EventOccurrences")
                        .HasForeignKey("EventId")
                        .HasConstraintName("event_occurrences_event_id_fkey");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("JSEA_Application.Models.ExperienceDetail", b =>
                {
                    b.HasOne("JSEA_Application.Models.User", "FeaturedByUser")
                        .WithMany("ExperienceDetailFeaturedByUsers")
                        .HasForeignKey("FeaturedByUserId")
                        .HasConstraintName("experience_details_featured_by_user_id_fkey");

                    b.HasOne("JSEA_Application.Models.User", "VerifiedByUser")
                        .WithMany("ExperienceDetailVerifiedByUsers")
                        .HasForeignKey("VerifiedByUserId")
                        .HasConstraintName("experience_details_verified_by_user_id_fkey");

                    b.Navigation("FeaturedByUser");

                    b.Navigation("VerifiedByUser");
                });

            modelBuilder.Entity("JSEA_Application.Models.ExperiencePhoto", b =>
                {
                    b.HasOne("JSEA_Application.Models.MicroExperience", "Experience")
                        .WithMany("ExperiencePhotos")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("experience_photos_experience_id_fkey");

                    b.HasOne("JSEA_Application.Models.User", "UploadedByUser")
                        .WithMany("ExperiencePhotos")
                        .HasForeignKey("UploadedByUserId")
                        .HasConstraintName("experience_photos_uploaded_by_user_id_fkey");

                    b.Navigation("Experience");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("JSEA_Application.Models.Feedback", b =>
                {
                    b.HasOne("JSEA_Application.Models.MicroExperience", "Experience")
                        .WithMany("Feedbacks")
                        .HasForeignKey("ExperienceId")
                        .HasConstraintName("feedbacks_experience_id_fkey");

                    b.HasOne("JSEA_Application.Models.User", "Traveler")
                        .WithMany("Feedbacks")
                        .HasForeignKey("TravelerId")
                        .HasConstraintName("feedbacks_traveler_id_fkey");

                    b.HasOne("JSEA_Application.Models.Visit", "Visit")
                        .WithOne("Feedback")
                        .HasForeignKey("JSEA_Application.Models.Feedback", "VisitId")
                        .HasConstraintName("feedbacks_visit_id_fkey");

                    b.Navigation("Experience");

                    b.Navigation("Traveler");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("JSEA_Application.Models.Journey", b =>
                {
                    b.HasOne("JSEA_Application.Models.User", "Traveler")
                        .WithMany("Journeys")
                        .HasForeignKey("TravelerId")
                        .HasConstraintName("journeys_traveler_id_fkey");

                    b.Navigation("Traveler");
                });

            modelBuilder.Entity("JSEA_Application.Models.JourneySuggestion", b =>
                {
                    b.HasOne("JSEA_Application.Models.MicroExperience", "Experience")
                        .WithMany("JourneySuggestions")
                        .HasForeignKey("ExperienceId")
                        .HasConstraintName("journey_suggestions_experience_id_fkey");

                    b.HasOne("JSEA_Application.Models.Journey", "Journey")
                        .WithMany("JourneySuggestions")
                        .HasForeignKey("JourneyId")
                        .HasConstraintName("journey_suggestions_journey_id_fkey");

                    b.HasOne("JSEA_Application.Models.RouteSegment", "Segment")
                        .WithMany("JourneySuggestions")
                        .HasForeignKey("SegmentId")
                        .HasConstraintName("journey_suggestions_segment_id_fkey");

                    b.Navigation("Experience");

                    b.Navigation("Journey");

                    b.Navigation("Segment");
                });

            modelBuilder.Entity("JSEA_Application.Models.JourneyWaypoint", b =>
                {
                    b.HasOne("JSEA_Application.Models.MicroExperience", "Experience")
                        .WithMany("JourneyWaypoints")
                        .HasForeignKey("ExperienceId")
                        .HasConstraintName("journey_waypoints_experience_id_fkey");

                    b.HasOne("JSEA_Application.Models.Journey", "Journey")
                        .WithMany("JourneyWaypoints")
                        .HasForeignKey("JourneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("journey_waypoints_journey_id_fkey");

                    b.Navigation("Experience");

                    b.Navigation("Journey");
                });

            modelBuilder.Entity("JSEA_Application.Models.MicroExperience", b =>
                {
                    b.HasOne("JSEA_Application.Models.Category", "Category")
                        .WithMany("MicroExperiences")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("micro_experiences_category_id_fkey");

                    b.HasOne("JSEA_Application.Models.ExperienceDetail", "IdNavigation")
                        .WithOne("MicroExperience")
                        .HasForeignKey("JSEA_Application.Models.MicroExperience", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("micro_experiences_id_fkey1");

                    b.HasOne("JSEA_Application.Models.ExperienceMetric", "Id1")
                        .WithOne("MicroExperience")
                        .HasForeignKey("JSEA_Application.Models.MicroExperience", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("micro_experiences_id_fkey");

                    b.HasOne("JSEA_Application.Models.User", "UploadedByUser")
                        .WithMany("MicroExperiences")
                        .HasForeignKey("UploadedByUserId")
                        .HasConstraintName("micro_experiences_uploaded_by_user_id_fkey");

                    b.Navigation("Category");

                    b.Navigation("Id1");

                    b.Navigation("IdNavigation");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("JSEA_Application.Models.Notification", b =>
                {
                    b.HasOne("JSEA_Application.Models.MicroExperience", "RelatedExperience")
                        .WithMany("Notifications")
                        .HasForeignKey("RelatedExperienceId")
                        .HasConstraintName("notifications_related_experience_id_fkey");

                    b.HasOne("JSEA_Application.Models.Journey", "RelatedJourney")
                        .WithMany("Notifications")
                        .HasForeignKey("RelatedJourneyId")
                        .HasConstraintName("notifications_related_journey_id_fkey");

                    b.HasOne("JSEA_Application.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .HasConstraintName("notifications_user_id_fkey");

                    b.Navigation("RelatedExperience");

                    b.Navigation("RelatedJourney");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JSEA_Application.Models.Rating", b =>
                {
                    b.HasOne("JSEA_Application.Models.MicroExperience", "Experience")
                        .WithMany("Ratings")
                        .HasForeignKey("ExperienceId")
                        .HasConstraintName("ratings_experience_id_fkey");

                    b.HasOne("JSEA_Application.Models.User", "Traveler")
                        .WithMany("Ratings")
                        .HasForeignKey("TravelerId")
                        .HasConstraintName("ratings_traveler_id_fkey");

                    b.HasOne("JSEA_Application.Models.Visit", "Visit")
                        .WithOne("Rating")
                        .HasForeignKey("JSEA_Application.Models.Rating", "VisitId")
                        .HasConstraintName("ratings_visit_id_fkey");

                    b.Navigation("Experience");

                    b.Navigation("Traveler");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("JSEA_Application.Models.RefreshToken", b =>
                {
                    b.HasOne("JSEA_Application.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("refresh_tokens_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JSEA_Application.Models.RouteSegment", b =>
                {
                    b.HasOne("JSEA_Application.Models.Journey", "Journey")
                        .WithMany("RouteSegments")
                        .HasForeignKey("JourneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("route_segments_journey_id_fkey");

                    b.Navigation("Journey");
                });

            modelBuilder.Entity("JSEA_Application.Models.SuggestionInteraction", b =>
                {
                    b.HasOne("JSEA_Application.Models.JourneySuggestion", "Suggestion")
                        .WithMany("SuggestionInteractions")
                        .HasForeignKey("SuggestionId")
                        .HasConstraintName("suggestion_interactions_suggestion_id_fkey");

                    b.Navigation("Suggestion");
                });

            modelBuilder.Entity("JSEA_Application.Models.SystemConfig", b =>
                {
                    b.HasOne("JSEA_Application.Models.User", "UpdatedByUser")
                        .WithMany("SystemConfigs")
                        .HasForeignKey("UpdatedByUserId")
                        .HasConstraintName("system_configs_updated_by_user_id_fkey");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("JSEA_Application.Models.Transaction", b =>
                {
                    b.HasOne("JSEA_Application.Models.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .HasConstraintName("transactions_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JSEA_Application.Models.User", b =>
                {
                    b.HasOne("JSEA_Application.Models.UserProfile", "IdNavigation")
                        .WithOne("User")
                        .HasForeignKey("JSEA_Application.Models.User", "Id")
                        .HasPrincipalKey("JSEA_Application.Models.UserProfile", "UserId")
                        .IsRequired()
                        .HasConstraintName("users_id_fkey");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("JSEA_Application.Models.UserFavorite", b =>
                {
                    b.HasOne("JSEA_Application.Models.MicroExperience", "Experience")
                        .WithMany("UserFavorites")
                        .HasForeignKey("ExperienceId")
                        .IsRequired()
                        .HasConstraintName("user_favorites_experience_id_fkey");

                    b.HasOne("JSEA_Application.Models.User", "User")
                        .WithMany("UserFavorites")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("user_favorites_user_id_fkey");

                    b.Navigation("Experience");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JSEA_Application.Models.UserPackage", b =>
                {
                    b.HasOne("JSEA_Application.Models.Package", "Package")
                        .WithMany("UserPackages")
                        .HasForeignKey("PackageId")
                        .HasConstraintName("user_packages_package_id_fkey");

                    b.HasOne("JSEA_Application.Models.User", "User")
                        .WithMany("UserPackages")
                        .HasForeignKey("UserId")
                        .HasConstraintName("user_packages_user_id_fkey");

                    b.Navigation("Package");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JSEA_Application.Models.Visit", b =>
                {
                    b.HasOne("JSEA_Application.Models.MicroExperience", "Experience")
                        .WithMany("Visits")
                        .HasForeignKey("ExperienceId")
                        .HasConstraintName("visits_experience_id_fkey");

                    b.HasOne("JSEA_Application.Models.Feedback", "IdNavigation")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JSEA_Application.Models.Rating", "Id1")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JSEA_Application.Models.Journey", "Journey")
                        .WithMany("Visits")
                        .HasForeignKey("JourneyId")
                        .HasConstraintName("visits_journey_id_fkey");

                    b.HasOne("JSEA_Application.Models.User", "Traveler")
                        .WithMany("Visits")
                        .HasForeignKey("TravelerId")
                        .HasConstraintName("visits_traveler_id_fkey");

                    b.Navigation("Experience");

                    b.Navigation("Id1");

                    b.Navigation("IdNavigation");

                    b.Navigation("Journey");

                    b.Navigation("Traveler");
                });

            modelBuilder.Entity("JSEA_Application.Models.Category", b =>
                {
                    b.Navigation("MicroExperiences");
                });

            modelBuilder.Entity("JSEA_Application.Models.Event", b =>
                {
                    b.Navigation("EventOccurrences");
                });

            modelBuilder.Entity("JSEA_Application.Models.ExperienceDetail", b =>
                {
                    b.Navigation("MicroExperience");
                });

            modelBuilder.Entity("JSEA_Application.Models.ExperienceMetric", b =>
                {
                    b.Navigation("MicroExperience");
                });

            modelBuilder.Entity("JSEA_Application.Models.Journey", b =>
                {
                    b.Navigation("JourneySuggestions");

                    b.Navigation("JourneyWaypoints");

                    b.Navigation("Notifications");

                    b.Navigation("RouteSegments");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("JSEA_Application.Models.JourneySuggestion", b =>
                {
                    b.Navigation("SuggestionInteractions");
                });

            modelBuilder.Entity("JSEA_Application.Models.MicroExperience", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("ExperiencePhotos");

                    b.Navigation("Feedbacks");

                    b.Navigation("JourneySuggestions");

                    b.Navigation("JourneyWaypoints");

                    b.Navigation("Notifications");

                    b.Navigation("Ratings");

                    b.Navigation("UserFavorites");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("JSEA_Application.Models.Package", b =>
                {
                    b.Navigation("UserPackages");
                });

            modelBuilder.Entity("JSEA_Application.Models.RouteSegment", b =>
                {
                    b.Navigation("JourneySuggestions");
                });

            modelBuilder.Entity("JSEA_Application.Models.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Events");

                    b.Navigation("ExperienceDetailFeaturedByUsers");

                    b.Navigation("ExperienceDetailVerifiedByUsers");

                    b.Navigation("ExperiencePhotos");

                    b.Navigation("Feedbacks");

                    b.Navigation("Journeys");

                    b.Navigation("MicroExperiences");

                    b.Navigation("Notifications");

                    b.Navigation("Ratings");

                    b.Navigation("RefreshTokens");

                    b.Navigation("SystemConfigs");

                    b.Navigation("Transactions");

                    b.Navigation("UserFavorites");

                    b.Navigation("UserPackages");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("JSEA_Application.Models.UserProfile", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("JSEA_Application.Models.Visit", b =>
                {
                    b.Navigation("Feedback");

                    b.Navigation("Rating");
                });
#pragma warning restore 612, 618
        }
    }
}
