// <auto-generated />
using System;
using System.Collections.Generic;
using System.Net;
using JSEA_Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JSEA_Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260228043757_AddRewardPointsToUserProfile")]
    partial class AddRewardPointsToUserProfile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "fuzzystrmatch");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JSEA_Application.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action_type");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<IPAddress>("IpAddress")
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<string>("NewValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_values");

                    b.Property<string>("OldValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_values");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("audit_logs_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("audit_logs");
                });

            modelBuilder.Entity("JSEA_Application.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("icon_url");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("categories_pkey");

                    b.HasIndex(new[] { "Name" }, "categories_name_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Slug" }, "categories_slug_key")
                        .IsUnique();

                    b.ToTable("categories");
                });

            modelBuilder.Entity("JSEA_Application.Models.EmailOtp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_at");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_used");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_verified");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("otp_code");

                    b.HasKey("Id")
                        .HasName("email_otps_pkey");

                    b.ToTable("email_otps");
                });

            modelBuilder.Entity("JSEA_Application.Models.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndDatetime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_datetime");

                    b.Property<string>("EventType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<Guid?>("ExperienceId")
                        .HasColumnType("uuid")
                        .HasColumnName("experience_id");

                    b.Property<string>("RecurrencePattern")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("recurrence_pattern");

                    b.Property<string>("RecurrenceRule")
                        .HasColumnType("text")
                        .HasColumnName("recurrence_rule");

                    b.Property<decimal?>("ScoreBoostFactor")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("score_boost_factor");

                    b.Property<DateTime?>("StartDatetime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_datetime");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<Guid?>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id")
                        .HasName("events_pkey");

                    b.HasIndex("ExperienceId");

                    b.ToTable("events");
                });

            modelBuilder.Entity("JSEA_Application.Models.EventOccurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTime?>("OccurrenceEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurrence_end");

                    b.Property<DateTime?>("OccurrenceStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurrence_start");

                    b.HasKey("Id")
                        .HasName("event_occurrences_pkey");

                    b.HasIndex("EventId");

                    b.ToTable("event_occurrences");
                });

            modelBuilder.Entity("JSEA_Application.Models.ExperienceDetail", b =>
                {
                    b.Property<Guid>("ExperienceId")
                        .HasColumnType("uuid")
                        .HasColumnName("experience_id");

                    b.Property<string>("AccessibilityInfo")
                        .HasColumnType("text")
                        .HasColumnName("accessibility_info");

                    b.Property<string>("CrowdLevel")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("crowd_level");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("FeaturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("featured_at");

                    b.Property<Guid?>("FeaturedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("featured_by_user_id");

                    b.Property<string>("ModerationNotes")
                        .HasColumnType("text")
                        .HasColumnName("moderation_notes");

                    b.Property<string>("OpeningHours")
                        .HasColumnType("jsonb")
                        .HasColumnName("opening_hours");

                    b.Property<string>("PriceRange")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("price_range");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("SafetyNotes")
                        .HasColumnType("text")
                        .HasColumnName("safety_notes");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.Property<Guid?>("VerifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("verified_by_user_id");

                    b.HasKey("ExperienceId")
                        .HasName("experience_details_pkey");

                    b.HasIndex("FeaturedByUserId");

                    b.HasIndex("VerifiedByUserId");

                    b.ToTable("experience_details");
                });

            modelBuilder.Entity("JSEA_Application.Models.ExperienceMetric", b =>
                {
                    b.Property<Guid>("ExperienceId")
                        .HasColumnType("uuid")
                        .HasColumnName("experience_id");

                    b.Property<decimal?>("AcceptanceRate")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("acceptance_rate");

                    b.Property<decimal?>("AvgRating")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(2, 1)
                        .HasColumnType("numeric(2,1)")
                        .HasDefaultValue(0m)
                        .HasColumnName("avg_rating");

                    b.Property<decimal?>("FeaturedScore")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("featured_score");

                    b.Property<DateTime?>("LastVisitDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_visit_date");

                    b.Property<int?>("TotalRatings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_ratings");

                    b.Property<int?>("TotalVisits")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_visits");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ExperienceId")
                        .HasName("experience_metrics_pkey");

                    b.ToTable("experience_metrics");
                });

            modelBuilder.Entity("JSEA_Application.Models.ExperiencePhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Caption")
                        .HasColumnType("text")
                        .HasColumnName("caption");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<Guid?>("ExperienceId")
                        .HasColumnType("uuid")
                        .HasColumnName("experience_id");

                    b.Property<bool?>("IsCover")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_cover");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("photo_url");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("thumbnail_url");

                    b.Property<Guid?>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id")
                        .HasName("experience_photos_pkey");

                    b.HasIndex("ExperienceId");

                    b.ToTable("experience_photos");
                });

            modelBuilder.Entity("JSEA_Application.Models.Feedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("ExperienceId")
                        .HasColumnType("uuid")
                        .HasColumnName("experience_id");

                    b.Property<string>("FeedbackText")
                        .HasColumnType("text")
                        .HasColumnName("feedback_text");

                    b.Property<string>("FlaggedReason")
                        .HasColumnType("text")
                        .HasColumnName("flagged_reason");

                    b.Property<bool?>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_approved");

                    b.Property<bool?>("IsFlagged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_flagged");

                    b.Property<Guid?>("TravelerId")
                        .HasColumnType("uuid")
                        .HasColumnName("traveler_id");

                    b.Property<Guid?>("VisitId")
                        .HasColumnType("uuid")
                        .HasColumnName("visit_id");

                    b.HasKey("Id")
                        .HasName("feedbacks_pkey");

                    b.HasIndex(new[] { "VisitId" }, "feedbacks_visit_id_key")
                        .IsUnique();

                    b.ToTable("feedbacks");
                });

            modelBuilder.Entity("JSEA_Application.Models.Journey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int?>("ActualDistanceMeters")
                        .HasColumnType("integer")
                        .HasColumnName("actual_distance_meters");

                    b.Property<LineString>("ActualRoutePath")
                        .HasColumnType("geography(LineString,4326)")
                        .HasColumnName("actual_route_path");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CurrentMood")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("current_mood");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("destination_address");

                    b.Property<Point>("DestinationLocation")
                        .HasColumnType("geography(Point,4326)")
                        .HasColumnName("destination_location");

                    b.Property<int?>("EstimatedDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_duration_minutes");

                    b.Property<int?>("MaxDetourDistanceMeters")
                        .HasColumnType("integer")
                        .HasColumnName("max_detour_distance_meters");

                    b.Property<string>("OriginAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("origin_address");

                    b.Property<Point>("OriginLocation")
                        .HasColumnType("geography(Point,4326)")
                        .HasColumnName("origin_location");

                    b.Property<int?>("PreferredStopDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("preferred_stop_duration_minutes");

                    b.Property<LineString>("RoutePath")
                        .HasColumnType("geography(LineString,4326)")
                        .HasColumnName("route_path");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<int?>("TimeBudgetMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("time_budget_minutes");

                    b.Property<int?>("TotalDistanceMeters")
                        .HasColumnType("integer")
                        .HasColumnName("total_distance_meters");

                    b.Property<Guid?>("TravelerId")
                        .HasColumnType("uuid")
                        .HasColumnName("traveler_id");

                    b.Property<string>("VehicleType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("vehicle_type");

                    b.HasKey("Id")
                        .HasName("journeys_pkey");

                    b.HasIndex("TravelerId");

                    b.ToTable("journeys");
                });

            modelBuilder.Entity("JSEA_Application.Models.JourneySuggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int?>("DetourDistanceMeters")
                        .HasColumnType("integer")
                        .HasColumnName("detour_distance_meters");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<int?>("EstimatedStopMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_stop_minutes");

                    b.Property<Guid?>("ExperienceId")
                        .HasColumnType("uuid")
                        .HasColumnName("experience_id");

                    b.Property<Guid?>("JourneyId")
                        .HasColumnType("uuid")
                        .HasColumnName("journey_id");

                    b.Property<decimal?>("RelevanceScore")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("relevance_score");

                    b.Property<Guid?>("SegmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("segment_id");

                    b.Property<DateTime?>("SuggestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("suggested_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("journey_suggestions_pkey");

                    b.HasIndex("ExperienceId");

                    b.HasIndex("JourneyId");

                    b.HasIndex("SegmentId");

                    b.ToTable("journey_suggestions");
                });

            modelBuilder.Entity("JSEA_Application.Models.JourneyWaypoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("ActualArrivalAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actual_arrival_at");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<DateTime?>("EstimatedArrivalAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("estimated_arrival_at");

                    b.Property<Guid?>("ExperienceId")
                        .HasColumnType("uuid")
                        .HasColumnName("experience_id");

                    b.Property<Guid?>("JourneyId")
                        .HasColumnType("uuid")
                        .HasColumnName("journey_id");

                    b.Property<Point>("Location")
                        .HasColumnType("geography(Point,4326)")
                        .HasColumnName("location");

                    b.Property<int?>("StopOrder")
                        .HasColumnType("integer")
                        .HasColumnName("stop_order");

                    b.HasKey("Id")
                        .HasName("journey_waypoints_pkey");

                    b.HasIndex("ExperienceId");

                    b.HasIndex("JourneyId");

                    b.ToTable("journey_waypoints");
                });

            modelBuilder.Entity("JSEA_Application.Models.MicroExperience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country")
                        .HasDefaultValueSql("'Vietnam'::character varying");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Point>("Location")
                        .HasColumnType("geography(Point,4326)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<List<string>>("PreferredTimes")
                        .HasColumnType("character varying(50)[]")
                        .HasColumnName("preferred_times");

                    b.Property<List<string>>("Seasonality")
                        .HasColumnType("character varying(50)[]")
                        .HasColumnName("seasonality");

                    b.Property<string>("Slug")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<List<string>>("SuitableMoods")
                        .HasColumnType("character varying(50)[]")
                        .HasColumnName("suitable_moods");

                    b.Property<List<string>>("Tags")
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_user_id");

                    b.Property<List<string>>("WeatherSuitability")
                        .HasColumnType("character varying(50)[]")
                        .HasColumnName("weather_suitability");

                    b.HasKey("Id")
                        .HasName("micro_experiences_pkey");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UploadedByUserId");

                    b.HasIndex(new[] { "Slug" }, "micro_experiences_slug_key")
                        .IsUnique();

                    b.ToTable("micro_experiences");
                });

            modelBuilder.Entity("JSEA_Application.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("notification_type");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<Guid?>("RelatedExperienceId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_experience_id");

                    b.Property<Guid?>("RelatedJourneyId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_journey_id");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("notifications_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("JSEA_Application.Models.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Benefit")
                        .HasColumnType("jsonb")
                        .HasColumnName("benefit");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool?>("IsPopular")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_popular");

                    b.Property<int?>("Km")
                        .HasColumnType("integer")
                        .HasColumnName("km");

                    b.Property<decimal?>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price");

                    b.Property<decimal?>("SalePrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("sale_price");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("packages_pkey");

                    b.ToTable("packages");
                });

            modelBuilder.Entity("JSEA_Application.Models.Rating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("ExperienceId")
                        .HasColumnType("uuid")
                        .HasColumnName("experience_id");

                    b.Property<int?>("Rating1")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<Guid?>("TravelerId")
                        .HasColumnType("uuid")
                        .HasColumnName("traveler_id");

                    b.Property<Guid?>("VisitId")
                        .HasColumnType("uuid")
                        .HasColumnName("visit_id");

                    b.HasKey("Id")
                        .HasName("ratings_pkey");

                    b.HasIndex(new[] { "VisitId" }, "ratings_visit_id_key")
                        .IsUnique();

                    b.ToTable("ratings");
                });

            modelBuilder.Entity("JSEA_Application.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("refresh_tokens_pkey");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "TokenHash" }, "refresh_tokens_token_hash_key")
                        .IsUnique();

                    b.ToTable("refresh_tokens");
                });

            modelBuilder.Entity("JSEA_Application.Models.RouteSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int?>("DistanceMeters")
                        .HasColumnType("integer")
                        .HasColumnName("distance_meters");

                    b.Property<int?>("EstimatedDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_duration_minutes");

                    b.Property<bool?>("IsBusy")
                        .HasColumnType("boolean")
                        .HasColumnName("is_busy");

                    b.Property<bool?>("IsCulturalArea")
                        .HasColumnType("boolean")
                        .HasColumnName("is_cultural_area");

                    b.Property<bool?>("IsScenic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_scenic");

                    b.Property<Guid?>("JourneyId")
                        .HasColumnType("uuid")
                        .HasColumnName("journey_id");

                    b.Property<int?>("SegmentOrder")
                        .HasColumnType("integer")
                        .HasColumnName("segment_order");

                    b.Property<LineString>("SegmentPath")
                        .HasColumnType("geography(LineString,4326)")
                        .HasColumnName("segment_path");

                    b.HasKey("Id")
                        .HasName("route_segments_pkey");

                    b.HasIndex("JourneyId");

                    b.ToTable("route_segments");
                });

            modelBuilder.Entity("JSEA_Application.Models.SuggestionInteraction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("InteractedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("interacted_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("InteractionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("interaction_type");

                    b.Property<Guid?>("SuggestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("suggestion_id");

                    b.HasKey("Id")
                        .HasName("suggestion_interactions_pkey");

                    b.HasIndex("SuggestionId");

                    b.ToTable("suggestion_interactions");
                });

            modelBuilder.Entity("JSEA_Application.Models.SystemConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ConfigKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("config_key");

                    b.Property<string>("ConfigValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("config_value");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("system_configs_pkey");

                    b.HasIndex(new[] { "ConfigKey" }, "system_configs_config_key_key")
                        .IsUnique();

                    b.ToTable("system_configs");
                });

            modelBuilder.Entity("JSEA_Application.Models.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long?>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ItemSnapshot")
                        .HasColumnType("jsonb")
                        .HasColumnName("item_snapshot");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_method");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("transactions_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("transactions");
                });

            modelBuilder.Entity("JSEA_Application.Models.TravelStyle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Descripton")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descripton");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("travel_styles");
                });

            modelBuilder.Entity("JSEA_Application.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool?>("EmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("email_verified");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<bool?>("PhoneVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("phone_verified");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex(new[] { "Email" }, "users_email_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Phone" }, "users_phone_key")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("JSEA_Application.Models.UserFavorite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ExperienceId")
                        .HasColumnType("uuid")
                        .HasColumnName("experience_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("user_favorites_pkey");

                    b.HasIndex("ExperienceId");

                    b.HasIndex("UserId");

                    b.ToTable("user_favorites");
                });

            modelBuilder.Entity("JSEA_Application.Models.UserPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("ActivatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<Guid?>("PackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("user_packages_pkey");

                    b.HasIndex("PackageId");

                    b.HasIndex("UserId");

                    b.ToTable("user_packages");
                });

            modelBuilder.Entity("JSEA_Application.Models.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AccessibilityNeeds")
                        .HasColumnType("text")
                        .HasColumnName("accessibility_needs");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("department");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<List<string>>("Interests")
                        .HasColumnType("text[]")
                        .HasColumnName("interests");

                    b.Property<string>("Permissions")
                        .HasColumnType("jsonb")
                        .HasColumnName("permissions");

                    b.Property<int>("RewardPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("reward_points");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("user_profiles_pkey");

                    b.HasIndex(new[] { "UserId" }, "user_profiles_user_id_key")
                        .IsUnique();

                    b.ToTable("user_profiles");
                });

            modelBuilder.Entity("JSEA_Application.Models.UserVibe", b =>
                {
                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_profile_id");

                    b.Property<Guid>("TravelStyleId")
                        .HasColumnType("uuid")
                        .HasColumnName("travel_style_id");

                    b.Property<DateTime>("SelectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("selected_at");

                    b.HasKey("UserProfileId", "TravelStyleId")
                        .HasName("user_vibes_pkey");

                    b.HasIndex("TravelStyleId");

                    b.ToTable("user_vibes");
                });

            modelBuilder.Entity("JSEA_Application.Models.Visit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int?>("ActualDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("actual_duration_minutes");

                    b.Property<Guid?>("ExperienceId")
                        .HasColumnType("uuid")
                        .HasColumnName("experience_id");

                    b.Property<Guid?>("JourneyId")
                        .HasColumnType("uuid")
                        .HasColumnName("journey_id");

                    b.Property<List<string>>("PhotoUrls")
                        .HasColumnType("text[]")
                        .HasColumnName("photo_urls");

                    b.Property<Guid?>("TravelerId")
                        .HasColumnType("uuid")
                        .HasColumnName("traveler_id");

                    b.Property<DateTime?>("VisitedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("visited_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("visits_pkey");

                    b.HasIndex("ExperienceId");

                    b.HasIndex("JourneyId");

                    b.HasIndex("TravelerId");

                    b.ToTable("visits");
                });

            modelBuilder.Entity("JSEA_Application.Models.AuditLog", b =>
                {
                    b.HasOne("JSEA_Application.Models.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_audit_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JSEA_Application.Models.Event", b =>
                {
                    b.HasOne("JSEA_Application.Models.MicroExperience", "Experience")
                        .WithMany("Events")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_event_exp");

                    b.Navigation("Experience");
                });

            modelBuilder.Entity("JSEA_Application.Models.EventOccurrence", b =>
                {
                    b.HasOne("JSEA_Application.Models.Event", "Event")
                        .WithMany("EventOccurrences")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_occ_event");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("JSEA_Application.Models.ExperienceDetail", b =>
                {
                    b.HasOne("JSEA_Application.Models.MicroExperience", "Experience")
                        .WithOne("ExperienceDetail")
                        .HasForeignKey("JSEA_Application.Models.ExperienceDetail", "ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_detail_exp");

                    b.HasOne("JSEA_Application.Models.User", "FeaturedByUser")
                        .WithMany("ExperienceDetailFeaturedByUsers")
                        .HasForeignKey("FeaturedByUserId")
                        .HasConstraintName("fk_detail_featured");

                    b.HasOne("JSEA_Application.Models.User", "VerifiedByUser")
                        .WithMany("ExperienceDetailVerifiedByUsers")
                        .HasForeignKey("VerifiedByUserId")
                        .HasConstraintName("fk_detail_verifier");

                    b.Navigation("Experience");

                    b.Navigation("FeaturedByUser");

                    b.Navigation("VerifiedByUser");
                });

            modelBuilder.Entity("JSEA_Application.Models.ExperienceMetric", b =>
                {
                    b.HasOne("JSEA_Application.Models.MicroExperience", "Experience")
                        .WithOne("ExperienceMetric")
                        .HasForeignKey("JSEA_Application.Models.ExperienceMetric", "ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_metric_exp");

                    b.Navigation("Experience");
                });

            modelBuilder.Entity("JSEA_Application.Models.ExperiencePhoto", b =>
                {
                    b.HasOne("JSEA_Application.Models.MicroExperience", "Experience")
                        .WithMany("ExperiencePhotos")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_photo_exp");

                    b.Navigation("Experience");
                });

            modelBuilder.Entity("JSEA_Application.Models.Feedback", b =>
                {
                    b.HasOne("JSEA_Application.Models.Visit", "Visit")
                        .WithOne("Feedback")
                        .HasForeignKey("JSEA_Application.Models.Feedback", "VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_feedback_visit");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("JSEA_Application.Models.Journey", b =>
                {
                    b.HasOne("JSEA_Application.Models.User", "Traveler")
                        .WithMany("Journeys")
                        .HasForeignKey("TravelerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_journey_user");

                    b.Navigation("Traveler");
                });

            modelBuilder.Entity("JSEA_Application.Models.JourneySuggestion", b =>
                {
                    b.HasOne("JSEA_Application.Models.MicroExperience", "Experience")
                        .WithMany("JourneySuggestions")
                        .HasForeignKey("ExperienceId")
                        .HasConstraintName("fk_sugg_exp");

                    b.HasOne("JSEA_Application.Models.Journey", "Journey")
                        .WithMany("JourneySuggestions")
                        .HasForeignKey("JourneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_sugg_journey");

                    b.HasOne("JSEA_Application.Models.RouteSegment", "Segment")
                        .WithMany("JourneySuggestions")
                        .HasForeignKey("SegmentId")
                        .HasConstraintName("fk_sugg_segment");

                    b.Navigation("Experience");

                    b.Navigation("Journey");

                    b.Navigation("Segment");
                });

            modelBuilder.Entity("JSEA_Application.Models.JourneyWaypoint", b =>
                {
                    b.HasOne("JSEA_Application.Models.MicroExperience", "Experience")
                        .WithMany("JourneyWaypoints")
                        .HasForeignKey("ExperienceId")
                        .HasConstraintName("fk_waypoint_exp");

                    b.HasOne("JSEA_Application.Models.Journey", "Journey")
                        .WithMany("JourneyWaypoints")
                        .HasForeignKey("JourneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_waypoint_journey");

                    b.Navigation("Experience");

                    b.Navigation("Journey");
                });

            modelBuilder.Entity("JSEA_Application.Models.MicroExperience", b =>
                {
                    b.HasOne("JSEA_Application.Models.Category", "Category")
                        .WithMany("MicroExperiences")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_exp_cat");

                    b.HasOne("JSEA_Application.Models.User", "UploadedByUser")
                        .WithMany("MicroExperiences")
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_exp_user");

                    b.Navigation("Category");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("JSEA_Application.Models.Notification", b =>
                {
                    b.HasOne("JSEA_Application.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_notif_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JSEA_Application.Models.Rating", b =>
                {
                    b.HasOne("JSEA_Application.Models.Visit", "Visit")
                        .WithOne("Rating")
                        .HasForeignKey("JSEA_Application.Models.Rating", "VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_rating_visit");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("JSEA_Application.Models.RefreshToken", b =>
                {
                    b.HasOne("JSEA_Application.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_token_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JSEA_Application.Models.RouteSegment", b =>
                {
                    b.HasOne("JSEA_Application.Models.Journey", "Journey")
                        .WithMany("RouteSegments")
                        .HasForeignKey("JourneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_segment_journey");

                    b.Navigation("Journey");
                });

            modelBuilder.Entity("JSEA_Application.Models.SuggestionInteraction", b =>
                {
                    b.HasOne("JSEA_Application.Models.JourneySuggestion", "Suggestion")
                        .WithMany("SuggestionInteractions")
                        .HasForeignKey("SuggestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_interact_sugg");

                    b.Navigation("Suggestion");
                });

            modelBuilder.Entity("JSEA_Application.Models.Transaction", b =>
                {
                    b.HasOne("JSEA_Application.Models.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_trans_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JSEA_Application.Models.UserFavorite", b =>
                {
                    b.HasOne("JSEA_Application.Models.MicroExperience", "Experience")
                        .WithMany("UserFavorites")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fav_exp");

                    b.HasOne("JSEA_Application.Models.User", "User")
                        .WithMany("UserFavorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fav_user");

                    b.Navigation("Experience");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JSEA_Application.Models.UserPackage", b =>
                {
                    b.HasOne("JSEA_Application.Models.Package", "Package")
                        .WithMany("UserPackages")
                        .HasForeignKey("PackageId")
                        .HasConstraintName("fk_upkg_pkg");

                    b.HasOne("JSEA_Application.Models.User", "User")
                        .WithMany("UserPackages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_upkg_user");

                    b.Navigation("Package");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JSEA_Application.Models.UserProfile", b =>
                {
                    b.HasOne("JSEA_Application.Models.User", "User")
                        .WithOne("UserProfile")
                        .HasForeignKey("JSEA_Application.Models.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_profile");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JSEA_Application.Models.UserVibe", b =>
                {
                    b.HasOne("JSEA_Application.Models.TravelStyle", "TravelStyle")
                        .WithMany("UserVibes")
                        .HasForeignKey("TravelStyleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JSEA_Application.Models.UserProfile", "UserProfile")
                        .WithMany("UserVibes")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TravelStyle");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("JSEA_Application.Models.Visit", b =>
                {
                    b.HasOne("JSEA_Application.Models.MicroExperience", "Experience")
                        .WithMany("Visits")
                        .HasForeignKey("ExperienceId")
                        .HasConstraintName("fk_visit_exp");

                    b.HasOne("JSEA_Application.Models.Journey", "Journey")
                        .WithMany("Visits")
                        .HasForeignKey("JourneyId")
                        .HasConstraintName("fk_visit_journey");

                    b.HasOne("JSEA_Application.Models.User", "Traveler")
                        .WithMany("Visits")
                        .HasForeignKey("TravelerId")
                        .HasConstraintName("fk_visit_user");

                    b.Navigation("Experience");

                    b.Navigation("Journey");

                    b.Navigation("Traveler");
                });

            modelBuilder.Entity("JSEA_Application.Models.Category", b =>
                {
                    b.Navigation("MicroExperiences");
                });

            modelBuilder.Entity("JSEA_Application.Models.Event", b =>
                {
                    b.Navigation("EventOccurrences");
                });

            modelBuilder.Entity("JSEA_Application.Models.Journey", b =>
                {
                    b.Navigation("JourneySuggestions");

                    b.Navigation("JourneyWaypoints");

                    b.Navigation("RouteSegments");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("JSEA_Application.Models.JourneySuggestion", b =>
                {
                    b.Navigation("SuggestionInteractions");
                });

            modelBuilder.Entity("JSEA_Application.Models.MicroExperience", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("ExperienceDetail");

                    b.Navigation("ExperienceMetric");

                    b.Navigation("ExperiencePhotos");

                    b.Navigation("JourneySuggestions");

                    b.Navigation("JourneyWaypoints");

                    b.Navigation("UserFavorites");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("JSEA_Application.Models.Package", b =>
                {
                    b.Navigation("UserPackages");
                });

            modelBuilder.Entity("JSEA_Application.Models.RouteSegment", b =>
                {
                    b.Navigation("JourneySuggestions");
                });

            modelBuilder.Entity("JSEA_Application.Models.TravelStyle", b =>
                {
                    b.Navigation("UserVibes");
                });

            modelBuilder.Entity("JSEA_Application.Models.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("ExperienceDetailFeaturedByUsers");

                    b.Navigation("ExperienceDetailVerifiedByUsers");

                    b.Navigation("Journeys");

                    b.Navigation("MicroExperiences");

                    b.Navigation("Notifications");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Transactions");

                    b.Navigation("UserFavorites");

                    b.Navigation("UserPackages");

                    b.Navigation("UserProfile");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("JSEA_Application.Models.UserProfile", b =>
                {
                    b.Navigation("UserVibes");
                });

            modelBuilder.Entity("JSEA_Application.Models.Visit", b =>
                {
                    b.Navigation("Feedback");

                    b.Navigation("Rating");
                });
#pragma warning restore 612, 618
        }
    }
}
