@startuml 12d - Delete Micro-Experience
!theme plain
skinparam sequenceMessageAlign center
skinparam responseMessageBelowArrow true
skinparam linetype ortho

actor "Operation Staff" as OpStaff
participant "MicroExpManagementPage\n<<UI>>" as MicroUI
participant "MicroExperienceController\n<<controller>>" as MicroController
participant "MicroExperienceService\n<<service>>" as MicroService
participant "MicroExperienceRepository\n<<repository>>" as MicroRepo
database "JSEADatabase" as DB

OpStaff -> MicroUI : 1. deleteMicroExperience(id)
activate MicroUI
activate OpStaff
MicroUI -> MicroController : 2. DELETE /micro-experiences/{id}
activate MicroController
MicroController -> MicroService : 3. deleteAsync(id)
activate MicroService

MicroService -> MicroRepo : 4. getByIdAsync(id)
activate MicroRepo
MicroRepo -> DB : 5. SELECT FROM micro_experiences
activate DB
DB --> MicroRepo : 5.1 result
MicroRepo --> MicroService : 4.1 microExperience
deactivate DB
deactivate MicroRepo

alt not found
    MicroService --> MicroController : 3.1 notFound()
  
    MicroController --> MicroUI : 2.1 showError()

    MicroUI --> OpStaff : 1.1 displayError()

else found
    
    MicroService -> MicroRepo : 6. deleteAsync(id)
    activate MicroRepo
    MicroRepo -> DB : 7. DELETE FROM micro_experiences
    activate DB
    DB --> MicroRepo : 7.1 deleteResult
    MicroRepo --> MicroService : 6.1 deleted
    deactivate DB
    deactivate MicroRepo

    MicroService --> MicroController : 3.2 deleted()
    deactivate MicroService
    MicroController --> MicroUI : 2.2 deleteResponse()
    deactivate MicroController
    MicroUI --> OpStaff : 1.2 showDeleted()
    deactivate MicroUI
    deactivate OpStaff
end
@enduml
